// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtb7YGWVnyyCYwaxuPp2Hxpt-ctc-n_hE',
    appId: '1:949883842083:web:f35c5a581b889fb0840b96',
    messagingSenderId: '949883842083',
    projectId: 'quiz-app-e6582',
    authDomain: 'quiz-app-e6582.firebaseapp.com',
    storageBucket: 'quiz-app-e6582.firebasestorage.app',
    measurementId: 'G-ZETVNE4H51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU50x0CwGmQPj0Ms4n6IRy9y_6tmL-H28',
    appId: '1:949883842083:android:fae70fa6ef116e54840b96',
    messagingSenderId: '949883842083',
    projectId: 'quiz-app-e6582',
    storageBucket: 'quiz-app-e6582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_oFB_nxmzA3-o1AMg2Xll2V3vASAJdBM',
    appId: '1:949883842083:ios:0bf98e5590ea51fb840b96',
    messagingSenderId: '949883842083',
    projectId: 'quiz-app-e6582',
    storageBucket: 'quiz-app-e6582.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_oFB_nxmzA3-o1AMg2Xll2V3vASAJdBM',
    appId: '1:949883842083:ios:0bf98e5590ea51fb840b96',
    messagingSenderId: '949883842083',
    projectId: 'quiz-app-e6582',
    storageBucket: 'quiz-app-e6582.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtb7YGWVnyyCYwaxuPp2Hxpt-ctc-n_hE',
    appId: '1:949883842083:web:004935979ff56754840b96',
    messagingSenderId: '949883842083',
    projectId: 'quiz-app-e6582',
    authDomain: 'quiz-app-e6582.firebaseapp.com',
    storageBucket: 'quiz-app-e6582.firebasestorage.app',
    measurementId: 'G-C1VHJRK8L7',
  );
}
